CREATE DATABASE IF NOT EXISTS Loja;
USE Loja;

CREATE TABLE Cliente (
 id INT PRIMARY KEY AUTO_INCREMENT,
 nome VARCHAR(60) NOT NULL,
 sobrenome VARCHAR(120) NOT NULL,
 endereco TEXT NOT NULL,
 cep INT(8) NOT NULL
);

CREATE TABLE Produto (
 id INT PRIMARY KEY AUTO_INCREMENT,
 quantidade INT DEFAULT 0,
 preco DECIMAL(6,2) NOT NULL,
 nome_produto VARCHAR(255)
);

CREATE TABLE Pedido (
 id INT PRIMARY KEY AUTO_INCREMENT,
 id_cliente INT NOT NULL,
 id_produto INT NOT NULL,
 quantidade INT DEFAULT 1,
 data TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE Pedido ADD CONSTRAINT FOREIGN KEY (id_cliente) REFERENCES Cliente (id);
ALTER TABLE Pedido ADD CONSTRAINT FOREIGN KEY (id_produto) REFERENCES Produto (id);